apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: julia
resources:
- namespace.yaml
- secrets
- config
- docker-secret
- statefulset.yaml
- service.yaml

# Example storage class AWS. It's referenced by deployment.
#- storageclass.yaml
