apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namespace: julia
resources:
  - sealed-rclone-secret.yaml

configurations:
  - configuration/sealed-secret-config.yaml 

generatorOptions:
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
    sealedsecrets.bitnami.com/namespace-wide: "true"

secretGenerator:
  - name: rclone-secret
    type: Opaque
    #env: rclone.env
